### ISSUE TITLE
dbt-starrocks's optimize demand

### ISSUE THREAD

**Issue by motto1314** [StarRocks/dbt-starrocks#9]
Dbt-starrocks has been preliminarily implemented, but it still needs to be optimized.
This is a parent issue for dbt-starrocks. We will add TODOs to this issue.
TODOs:
+ [ ] 1. Table Support `Duplicate Key`/`Unique Key`/`Primary Key` #4 
+ [ ] 2. Table Support `Aggregate Key` #5 
+ [ ] 3. Column Support `HLL` \ `BITMAP` \ `JSON` types #6 
+ [ ] 4. `Seeds` use `Stream Load` #7 
+ [ ] 5. Partition could `full refresh`  #8

**Comment by tomtom215** [comment]
Any status on this issue?
